### ISSUE TITLE
Move blacklist to Annotation

### ISSUE THREAD

**Issue by dashwav** [dashwav/yin-bot#30]
Currently I have the bot only post in non-blacklisted channels with a code snippet at the beginning of the command. https://github.com/dashwav/yin-bot/blob/master/cogs/rng.py#L45

This should be abstracted to an annotation ideally

**Comment by dashwav** [comment]
@nickalaskreynolds Did you end up doing this somewhere or am I misremembering?

**Comment by nickalaskreynolds** [comment]
In the latest PR I remove the need to make a decorator and just did it in the yinbot.py file in the `on_message` event. It should be under the <https://github.com/dashwav/yin-bot/pull/38/commits/89ada153491d1b3c8b5822b6bd6748a684fda3a2> commit.

**Comment by dashwav** [comment]
Oh, is that one guaranteed to run first? Because I know we use on_message a few times throughout the code

**Comment by dashwav** [comment]
Closing due to #38.
Will open new issue to improve
