### ISSUE TITLE
Reorganize run.py to import and run cogs in alphabetical order

### ISSUE THREAD

**Issue by dashwav** [dashwav/yin-bot#64]
This is unironically something that always bothers me

**Comment by ShadowDogger** [comment]
run.py will be cleaned by me.

**Comment by ShadowDogger** [comment]
#65

**Comment by nickalaskreynolds** [comment]
tbh, I think it could be handled more pythonically. Like just importing the cog module and looping through it or listing out all the cogs and then looping through. Will cut back on some of the repetitive nature. Something like this
```
initial_extensions = ['owner',
                      'general',
                      'moderation',
                      'administration',
                      'blacklist',
                      'logging']
    for cog in initial_extensions:
        bot.load_extension('cog.' + cog)
```

**Comment by pandaxtc** [comment]
The list of extensions to load could be in `config.yml`, which might be better than hard-coding them.
